name: Download Artifact

on: workflow_dispatch

jobs:
  upload:
    runs-on : ubuntu-latest
    steps:

      - name: create file
        run: echo "Hello" > artifact2.txt

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact2.txt

  download:
    runs-on : ubuntu-latest
    needs: upload
    steps:
      - name: download file
        uses: actions/download-artifact@v3
        with:
          name: artifact2
      - name: read file
        run: cat artifact2.txt