name: Hello Francois

on: workflow_dispatch

env:
  NAME: Francois

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Dit bonjour"
        if: ${{env.NAME != 'Francois'}}
        run: echo "Salut toi ! Tu n'est pas Francois ?! Oo"
      - name: "Coucou Francois"
        if: ${{env.NAME == 'Francois'}}
        run: echo "Salut $NAME !"